# Generated by Django 5.0.10 on 2025-06-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_status_alter_user_avatar_and_more'),
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
    ]
